import { useEffect, useMemo, useState, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
import { Search, Sparkles } from "lucide-react";
import "./design-system.css";
import "./card-system.css";

export type CardVariant="content"|"stat"|"chart"|"table"|"panel";
export function Card({children,className="",variant="content",...props}:HTMLAttributes<HTMLElement>&{children:ReactNode;variant?:CardVariant}){return <section data-ui-card={variant} className={`uiCard uiCard--${variant} ${className}`} {...props}>{children}</section>}
export function GlassCard({children,className="",...props}:HTMLAttributes<HTMLElement>&{children:ReactNode}){return <Card className={className} {...props}>{children}</Card>}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="uiPageHeader"><div>{eyebrow&&<span>{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<aside>{actions}</aside>}</header>}
type StatTone="purple"|"blue"|"cyan"|"green"|"orange";
const latinDigits=(value:string)=>value.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d)));
function AnimatedStatValue({value}:{value:ReactNode}){
  const parsed=useMemo(()=>{if(typeof value==="number")return {number:value,suffix:"",decimals:Number.isInteger(value)?0:2};if(typeof value!=="string")return null;const normalized=latinDigits(value).trim().replace(/[٬,]/g,"");const match=normalized.match(/^(-?\d+(?:\.\d+)?)\s*(.*)$/u);if(!match)return null;return {number:Number(match[1]),suffix:match[2]||"",decimals:(match[1].split(".")[1]||"").length}},[value]);
  const [shown,setShown]=useState(parsed?.number??0);
  useEffect(()=>{if(!parsed)return;if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setShown(parsed.number);return;}let frame=0;const started=performance.now();const duration=760;const tick=(now:number)=>{const progress=Math.min((now-started)/duration,1);setShown(parsed.number*(1-Math.pow(1-progress,3)));if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[parsed]);
  if(!parsed)return <>{value}</>;const formatted=shown.toLocaleString("fa-IR",{minimumFractionDigits:parsed.decimals,maximumFractionDigits:parsed.decimals});return <>{formatted}{parsed.suffix&&<b className="uiStatSuffix"> {parsed.suffix}</b>}</>;
}
function StatSparkline({data}:{data:number[]}){const points=useMemo(()=>{if(!data.length)return "";const min=Math.min(...data),max=Math.max(...data),range=max-min||1;return data.map((v,i)=>`${data.length===1?60:(i/(data.length-1))*120},${32-((v-min)/range)*25}`).join(" ")},[data]);if(!points)return null;return <svg className="uiStatSpark" viewBox="0 0 120 36" preserveAspectRatio="none" aria-hidden="true"><polyline points={points}/></svg>}
export function StatCard({title,value,hint,icon,tone="purple",trend,loading=false,data=[]}:{title:string;value:ReactNode;hint?:string;icon:ReactNode;tone?:StatTone;trend?:string;loading?:boolean;data?:number[]}){return <GlassCard className={`uiStat ${tone} ${loading?"loading":""}`}><i className="uiStatIcon">{icon}</i><div className="uiStatBody"><span>{title}</span><strong>{loading?"":<AnimatedStatValue value={value}/>}</strong>{hint&&<small>{hint}</small>}{trend&&<em>{trend}</em>}</div>{!loading&&<StatSparkline data={data}/>}</GlassCard>}
export function CardHeader({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <header className="uiCardHeader"><div>{subtitle&&<span>{subtitle}</span>}<h2>{title}</h2></div>{action}</header>}
export function ChartCard({title,subtitle,children,className=""}:{title:string;subtitle?:string;children:ReactNode;className?:string}){return <Card variant="chart" className={`uiChart ${className}`}><CardHeader title={title} subtitle={subtitle}/>{children}</Card>}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"success"|"warning"|"danger"|"info"|"purple"|"neutral"}){return <span className={`uiBadge ${tone}`}>{children}</span>}
export function SearchBar(props:InputHTMLAttributes<HTMLInputElement>){return <label className="uiSearch"><Search size={16}/><input {...props}/></label>}
export function DataTable({children,className=""}:{children:ReactNode;className?:string}){return <div className={`uiTableWrap ${className}`}><table className="uiTable">{children}</table></div>}
export function TableCard({title,subtitle,action,children,className=""}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <Card variant="table" className={className}>{title&&<CardHeader title={title} subtitle={subtitle} action={action}/>} {children}</Card>}
export function EmptyState({title,description}:{title:string;description?:string}){return <div className="uiEmpty"><Sparkles size={23}/><strong>{title}</strong>{description&&<span>{description}</span>}</div>}
export function Timeline({items,className=""}:{items:Array<{id:string;icon?:ReactNode;title:string;description?:string;meta?:string;tone?:"purple"|"cyan"|"green"|"orange"|"red"}>;className?:string}){return <div className={`uiTimeline ${className}`}>{items.map((item,index)=><article key={item.id} style={{animationDelay:`${index*.055}s`}}><i className={item.tone||"purple"}>{item.icon}</i><div><strong>{item.title}</strong>{item.description&&<p>{item.description}</p>}{item.meta&&<small>{item.meta}</small>}</div></article>)}</div>}
export function Modal({open,title,onClose,children,footer}:{open:boolean;title:string;onClose:()=>void;children:ReactNode;footer?:ReactNode}){if(!open)return null;return <div className="uiModalBackdrop" onMouseDown={onClose}><Card variant="panel" className="uiModal" onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><button onClick={onClose} aria-label="بستن">×</button></header><div>{children}</div>{footer&&<footer>{footer}</footer>}</Card></div>}
export function ActionButton({children,className="",...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`uiAction ${className}`} {...props}>{children}</button>}
