import {useEffect,useMemo,useState} from "react";
import {Calculator,Check,Eye,FileCheck2,FileClock,FileOutput,FilePlus2,Pencil,Plus,Search,Send,Trash2,WalletCards,X} from "lucide-react";
import {ActionButton,Badge,Card,DataTable,EmptyState,GlassCard,Modal,PageHeader,StatCard,TableCard} from "../components/ui/DesignSystem";
import {approveQuotation,convertQuotationToInvoice,createQuotation,deleteQuotation,getCustomers,getQuotations,getSalesUsers,rejectQuotation,updateQuotation,type QuotationItem,type QuotationRecord,type QuotationStatus} from "../services/api";
import {getCurrentUser} from "../utils/auth";import "./Quotations.css";import "./QuotationEnhancements.css";import "./QuotationWorkflow.css";
type Customer={id:number;name:string;phone:string;assignedToId:number|null};type SalesUser={id:number;name:string};
const labels:Record<QuotationStatus,string>={DRAFT:"پیش‌نویس",SENT:"ارسال شده",APPROVED:"تأیید شده",REJECTED:"رد شده",EXPIRED:"منقضی"};const tones={DRAFT:"neutral",SENT:"info",APPROVED:"success",REJECTED:"danger",EXPIRED:"warning"} as const;
const money=(v:number)=>`${Number(v||0).toLocaleString("fa-IR")} ریال`,blank=():QuotationItem=>({productName:"",quantity:1,unitPrice:0,discount:0}),local=(v?:string|null)=>v?new Date(v).toISOString().slice(0,16):"";
export default function Quotations(){
 const user=getCurrentUser(),[rows,setRows]=useState<QuotationRecord[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[users,setUsers]=useState<SalesUser[]>([]),[open,setOpen]=useState(false),[viewing,setViewing]=useState<QuotationRecord|null>(null),[editing,setEditing]=useState<QuotationRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[search,setSearch]=useState(""),[status,setStatus]=useState<"ALL"|QuotationStatus>("ALL"),[form,setForm]=useState({customerId:0,userId:0,quotationNumber:"",quotationDate:local(new Date().toISOString()),description:"",items:[blank()],discount:0,tax:0,validUntil:"",status:"DRAFT" as "DRAFT"|"SENT"});
 const load=async()=>{const[q,c]=await Promise.all([getQuotations(),getCustomers()]);setRows(q);setCustomers(c);if(user?.role==="ADMIN")setUsers(await getSalesUsers())};useEffect(()=>{void load().catch(e=>setError(e.response?.data?.message||"خطا در دریافت پیش‌فاکتورها"))},[]);
 const totals=useMemo(()=>{const gross=form.items.reduce((s,i)=>s+i.quantity*i.unitPrice,0),rowDiscount=form.items.reduce((s,i)=>s+Number(i.discount||0),0),subtotal=gross-rowDiscount;return{gross,rowDiscount,subtotal,total:Math.max(0,subtotal-form.discount+form.tax)}},[form]);
 const filtered=useMemo(()=>rows.filter(r=>{const q=search.trim().toLocaleLowerCase("fa");return(!q||r.customer?.name.toLocaleLowerCase("fa").includes(q)||r.quotationNumber.toLocaleLowerCase("fa").includes(q))&&(status==="ALL"||r.status===status)}),[rows,search,status]);
 const start=(row?:QuotationRecord)=>{setEditing(row||null);setForm(row?{customerId:row.customerId,userId:row.userId,quotationNumber:row.quotationNumber,quotationDate:local(row.quotationDate),description:row.description||"",items:row.items.map(i=>({productName:i.productName,quantity:i.quantity,unitPrice:i.unitPrice,discount:Number(i.discount||0)})),discount:row.discount,tax:row.tax,validUntil:local(row.validUntil),status:row.status==="SENT"?"SENT":"DRAFT"}:{customerId:0,userId:0,quotationNumber:"",quotationDate:local(new Date().toISOString()),description:"",items:[blank()],discount:0,tax:0,validUntil:"",status:"DRAFT"});setOpen(true)};
 const save=async()=>{setBusy(true);setError("");try{const customer=customers.find(c=>c.id===form.customerId),payload={...form,quotationNumber:form.quotationNumber.trim()||undefined,userId:user?.role==="ADMIN"?(form.userId||customer?.assignedToId||undefined):undefined,quotationDate:new Date(form.quotationDate).toISOString(),validUntil:form.validUntil?new Date(form.validUntil).toISOString():null};editing?await updateQuotation(editing.id,payload):await createQuotation(payload);setOpen(false);await load()}catch(e:any){setError(e.response?.data?.message||"ثبت انجام نشد")}finally{setBusy(false)}};
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await fn();await load()}catch(e:any){setError(e.response?.data?.message||"عملیات انجام نشد")}finally{setBusy(false)}};const item=(index:number,key:keyof QuotationItem,value:string|number)=>setForm(f=>({...f,items:f.items.map((i,n)=>n===index?{...i,[key]:value}:i)}));
 return <main className="quotationPage" dir="rtl"><PageHeader eyebrow="QUOTATION CRM" title="مرکز پیش‌فاکتورها" description="مدیریت چرخه پیش‌فاکتور از پیش‌نویس تا تبدیل به فاکتور فروش" actions={<ActionButton onClick={()=>start()}><FilePlus2/>پیش‌فاکتور جدید</ActionButton>}/>{error&&<div className="quotationError">{error}</div>}
 <div className="quotationStats"><StatCard title="تعداد کل" value={rows.length} icon={<FilePlus2/>} tone="cyan"/><StatCard title="مبلغ کل" value={money(rows.reduce((s,r)=>s+r.totalAmount,0))} icon={<WalletCards/>} tone="purple"/><StatCard title="تأیید شده" value={rows.filter(r=>r.status==="APPROVED").length} icon={<FileCheck2/>} tone="green"/><StatCard title="در انتظار" value={rows.filter(r=>r.status==="DRAFT"||r.status==="SENT").length} icon={<FileClock/>} tone="orange"/></div>
 <GlassCard className="quotationFilters"><label className="quotationSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام مشتری یا شماره پیش‌فاکتور"/></label><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="ALL">همه وضعیت‌ها</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></GlassCard>
 <TableCard className="quotationList"><header><div><small>QUOTATION PIPELINE</small><h2>جدول پیش‌فاکتورها</h2></div><span>{filtered.length.toLocaleString("fa-IR")} مورد</span></header>{filtered.length?<DataTable><thead><tr><th>شماره پیش‌فاکتور</th><th>مشتری</th><th>تاریخ</th><th>مبلغ کل</th><th>وضعیت</th><th>ایجاد کننده</th><th>عملیات</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.quotationNumber}</b></td><td>{r.customer?.name}</td><td>{new Date(r.quotationDate||r.createdAt).toLocaleDateString("fa-IR")}</td><td className="quotationMoney">{money(r.totalAmount)}</td><td><Badge tone={tones[r.status]}>{labels[r.status]}</Badge></td><td>{r.user?.name}</td><td><div className="quotationActions"><button title="مشاهده" onClick={()=>setViewing(r)}><Eye/></button>{r.status==="DRAFT"&&<button title="ارسال" onClick={()=>void act(()=>updateQuotation(r.id,{status:"SENT"}))}><Send/></button>}{["DRAFT","SENT"].includes(r.status)&&<><button title="ویرایش" onClick={()=>start(r)}><Pencil/></button><button className="approve" title="تأیید" onClick={()=>void act(()=>approveQuotation(r.id))}><Check/></button><button className="reject" title="رد کردن" onClick={()=>void act(()=>rejectQuotation(r.id))}><X/></button></>}{r.status==="APPROVED"&&!r.invoiceId&&<button className="convert" title="تبدیل به فاکتور فروش" onClick={()=>void act(()=>convertQuotationToInvoice(r.id))}><FileOutput/></button>}{r.invoiceId&&<Badge tone="success">{r.invoice?.invoiceNumber}</Badge>}{r.status!=="APPROVED"&&<button className="delete" title="حذف" onClick={()=>confirm("آیا این پیش‌فاکتور حذف شود؟")&&void act(()=>deleteQuotation(r.id))}><Trash2/></button>}</div></td></tr>)}</tbody></DataTable>:<EmptyState title="پیش‌فاکتوری وجود ندارد" description="پیش‌فاکتور جدید بسازید یا فیلترها را تغییر دهید."/>}</TableCard>
 <Modal open={open} title={editing?"ویرایش پیش‌فاکتور":"ایجاد پیش‌فاکتور"} onClose={()=>!busy&&setOpen(false)} footer={<><ActionButton className="secondary" onClick={()=>setOpen(false)}>انصراف</ActionButton><ActionButton disabled={busy||!form.customerId} onClick={()=>void save()}>{busy?"در حال ذخیره...":"ذخیره"}</ActionButton></>}><div className="quotationForm"><label>مشتری<select value={form.customerId} onChange={e=>{const id=+e.target.value,c=customers.find(x=>x.id===id);setForm(f=>({...f,customerId:id,userId:c?.assignedToId||f.userId}))}}><option value={0}>انتخاب مشتری</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} — {c.phone}</option>)}</select></label>{user?.role==="ADMIN"&&<label>کارشناس<select value={form.userId} onChange={e=>setForm(f=>({...f,userId:+e.target.value}))}><option value={0}>مسئول مشتری</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}<label>تاریخ<input type="datetime-local" value={form.quotationDate} onChange={e=>setForm(f=>({...f,quotationDate:e.target.value}))}/></label><label>شماره<input value={form.quotationNumber} onChange={e=>setForm(f=>({...f,quotationNumber:e.target.value}))} placeholder="تولید خودکار"/></label><label>اعتبار تا<input type="datetime-local" value={form.validUntil} onChange={e=>setForm(f=>({...f,validUntil:e.target.value}))}/></label><label>وضعیت<select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value as "DRAFT"|"SENT"}))}><option value="DRAFT">پیش‌نویس</option><option value="SENT">ارسال شده</option></select></label>
 <Card className="quotationItems"><header><h3>محصولات</h3><button onClick={()=>setForm(f=>({...f,items:[...f.items,blank()]}))}><Plus/>افزودن ردیف</button></header>{form.items.map((i,index)=><div className="quotationItem quotationItemExpanded" key={index}><input placeholder="نام محصول" value={i.productName} onChange={e=>item(index,"productName",e.target.value)}/><input title="تعداد" type="number" min="1" value={i.quantity} onChange={e=>item(index,"quantity",+e.target.value)}/><input title="قیمت واحد" type="number" min="0" value={i.unitPrice} onChange={e=>item(index,"unitPrice",+e.target.value)}/><input title="تخفیف ردیف" type="number" min="0" max={i.quantity*i.unitPrice} value={i.discount} onChange={e=>item(index,"discount",+e.target.value)}/><strong>{money(i.quantity*i.unitPrice-i.discount)}</strong><button disabled={form.items.length===1} onClick={()=>setForm(f=>({...f,items:f.items.filter((_,n)=>n!==index)}))}><Trash2/></button></div>)}</Card><label>تخفیف کل<input type="number" min="0" value={form.discount} onChange={e=>setForm(f=>({...f,discount:+e.target.value}))}/></label><label>مالیات<input type="number" min="0" value={form.tax} onChange={e=>setForm(f=>({...f,tax:+e.target.value}))}/></label><label className="quotationDescription">توضیحات<textarea value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></label><Card className="quotationSummary"><Calculator/><span>جمع کل <b>{money(totals.gross)}</b></span><span>تخفیف ردیف‌ها <b>{money(totals.rowDiscount)}</b></span><span>تخفیف کل <b>{money(form.discount)}</b></span><span>مالیات <b>{money(form.tax)}</b></span><span>مبلغ نهایی <strong>{money(totals.total)}</strong></span></Card></div></Modal>
 <Modal open={!!viewing} title={`مشاهده ${viewing?.quotationNumber||"پیش‌فاکتور"}`} onClose={()=>setViewing(null)}>{viewing&&<div className="quotationView"><Card className="quotationViewCard"><span>مشتری</span><strong>{viewing.customer.name}</strong></Card><Card className="quotationViewCard"><span>ایجاد کننده</span><strong>{viewing.user.name}</strong></Card><Card className="quotationViewCard"><span>تاریخ</span><strong>{new Date(viewing.quotationDate).toLocaleDateString("fa-IR")}</strong></Card><Card className="quotationViewCard"><span>وضعیت</span><Badge tone={tones[viewing.status]}>{labels[viewing.status]}</Badge></Card><DataTable><thead><tr><th>محصول</th><th>تعداد</th><th>قیمت واحد</th><th>تخفیف</th><th>مبلغ</th></tr></thead><tbody>{viewing.items.map((i,n)=><tr key={i.id||n}><td>{i.productName}</td><td>{i.quantity}</td><td>{money(i.unitPrice)}</td><td>{money(i.discount||0)}</td><td>{money(i.totalPrice||0)}</td></tr>)}</tbody></DataTable><p>{viewing.description||"بدون توضیحات"}</p><strong className="quotationViewTotal">مبلغ نهایی: {money(viewing.totalAmount)}</strong></div>}</Modal></main>}
