import { useEffect,useMemo,useState } from "react";
import { Banknote,RefreshCw,ShoppingBag,TrendingUp } from "lucide-react";
import { Area,AreaChart,ResponsiveContainer,Tooltip } from "recharts";
import { ActionButton,Badge,ChartCard,DataTable,PageHeader,StatCard } from "../components/ui/DesignSystem";
import { getSales } from "../services/api";
import "./Sales.css";
type Sale={id:number;productName:string;quantity:number;amount:number;createdAt:string;customer?:{name?:string;phone?:string};user?:{name?:string};salesperson?:{name?:string}};
const fa=(v:unknown)=>Number(v||0).toLocaleString("fa-IR");
export default function Sales(){const [sales,setSales]=useState<Sale[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{try{setLoading(true);setError("");const d=await getSales();setSales(Array.isArray(d)?d:[])}catch{setError("دریافت اطلاعات فروش ناموفق بود.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const revenue=useMemo(()=>sales.reduce((s,x)=>s+Number(x.amount||0),0),[sales]);const chart=sales.slice().reverse().map((s,i)=>({name:i+1,amount:Number(s.amount||0)}));return <main className="salesPage uiPage" dir="rtl"><PageHeader eyebrow="TAK CRM · SALES" title="مرکز فروش" description="فروش‌های ثبت‌شده و عملکرد کارشناسان را یکپارچه مشاهده کنید." actions={<ActionButton onClick={()=>void load()}><RefreshCw size={15}/> بروزرسانی</ActionButton>}/><section className="uiStats"><StatCard tone="purple" title="تعداد فروش" value={fa(sales.length)} hint="رکورد ثبت‌شده" icon={<ShoppingBag/>}/><StatCard tone="green" title="درآمد کل" value={`${fa(revenue)} ریال`} hint="مجموع فروش" icon={<Banknote/>}/><StatCard tone="cyan" title="میانگین فروش" value={`${fa(sales.length?revenue/sales.length:0)} ریال`} hint="میانگین هر رکورد" icon={<TrendingUp/>}/></section><ChartCard title="روند فروش‌های اخیر" subtitle="بر اساس داده واقعی فروش"><div className="modernSalesChart">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="salesArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#22d3ee" stopOpacity=".4"/><stop offset="1" stopColor="#22d3ee" stopOpacity="0"/></linearGradient></defs><Tooltip formatter={v=>[`${fa(v)} ریال`,"فروش"]}/><Area type="monotone" dataKey="amount" stroke="#22d3ee" strokeWidth={3} fill="url(#salesArea)"/></AreaChart></ResponsiveContainer>:<div className="salesState">هنوز فروشی ثبت نشده است.</div>}</div></ChartCard><ChartCard title="فهرست فروش‌ها" subtitle="آخرین تراکنش‌ها">{error&&<div className="salesState error">{error}</div>}{loading?<div className="salesState">در حال دریافت فروش‌ها…</div>:<DataTable><thead><tr><th>شماره</th><th>مشتری</th><th>محصول</th><th>تعداد</th><th>مبلغ</th><th>کارشناس</th><th>تاریخ</th><th>وضعیت</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>#{fa(s.id)}</td><td><strong>{s.customer?.name||"—"}</strong><small>{s.customer?.phone}</small></td><td>{s.productName}</td><td>{fa(s.quantity)}</td><td className="saleAmount">{fa(s.amount)} ریال</td><td>{s.user?.name||s.salesperson?.name||"—"}</td><td>{new Date(s.createdAt).toLocaleDateString("fa-IR")}</td><td><Badge tone="success">ثبت‌شده</Badge></td></tr>)}</tbody></DataTable>}</ChartCard></main>}
