import { useEffect, useRef, useState } from "react";
import { AlertCircle, CalendarDays, CalendarRange, CheckCircle2, Clock3, Download, Eye, FileSpreadsheet, History, RefreshCw, UploadCloud } from "lucide-react";
import { Link } from "react-router-dom";
import { ActionButton, Badge, DataTable, GlassCard, Modal, PageHeader } from "../components/ui/DesignSystem";
import { downloadSalesImportSample, getReportCharts, getReportSummary, getSalesImportHistory, importSalesReport, previewSalesReport, type SalesImportHistory, type SalesReportRow, type SalesReportType } from "../services/api";
import "./UploadSales.css";

type Preview={fileName:string;reportType:SalesReportType;totalRows:number;validRows:number;invalidRows:number;rows:SalesReportRow[];groups:Array<{period:string;sales:number;revenue:number}>;headers:string[];mapping:Record<string,string>;missingColumns:string[];analysis:{customer:boolean;date:boolean;product:boolean;amount:boolean}};
type Result={importedRows:number;failedRows:number;totalRows:number;errors:Array<{row:number;message:string}>};
const money=(value:unknown)=>Number(value||0).toLocaleString("fa-IR")+" ریال";
const reportTypes:Array<{key:SalesReportType;title:string;description:string}>=[
 {key:"DAILY",title:"گزارش روزانه",description:"گروه‌بندی فروش بر اساس روز"},
 {key:"MONTHLY",title:"گزارش ماهانه",description:"درآمد و مقایسه ماهانه"},
 {key:"YEARLY",title:"گزارش سالانه",description:"رشد و مجموع فروش سال"},
 {key:"CUSTOM",title:"بازه دلخواه",description:"گزارش یک دوره سفارشی"},
];
const mappingFields=[
 ["date","تاریخ فروش",true],["invoiceNumber","شماره فاکتور",true],["customerName","نام مشتری",false],
 ["customerPhone","تلفن مشتری",false],["productCode","کد کالا",false],["productName","نام کالا",true],
 ["quantity","تعداد",true],["amount","مبلغ",true],
] as const;

export default function UploadSales(){
 const inputRef=useRef<HTMLInputElement>(null);
 const [reportType,setReportType]=useState<SalesReportType>("DAILY");
 const [file,setFile]=useState<File|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[preview,setPreview]=useState<Preview|null>(null);
 const [progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<Result|null>(null);
 const [history,setHistory]=useState<SalesImportHistory[]>([]),[historyLoading,setHistoryLoading]=useState(true);
 const [selectedImport,setSelectedImport]=useState<SalesImportHistory|null>(null),[sampleLoading,setSampleLoading]=useState(false);
 const loadHistory=async()=>{try{setHistoryLoading(true);setHistory(await getSalesImportHistory())}catch{setHistory([])}finally{setHistoryLoading(false)}};
 useEffect(()=>{void loadHistory()},[]);
 const reset=()=>{setFile(null);setMapping({});setPreview(null);setResult(null);setProgress(0);setError("");if(inputRef.current)inputRef.current.value=""};
 const analyze=async(selected:File,map?:Record<string,string>)=>{setBusy(true);setError("");setResult(null);setProgress(1);try{const next=await previewSalesReport(selected,reportType,setProgress,map);setPreview(next);setMapping(next.mapping);setProgress(100)}catch(e:any){setError(e.response?.data?.message||"فایل گزارش قابل پردازش نیست.");setPreview(null)}finally{setBusy(false)}};
 const selectFile=async(selected?:File)=>{if(!selected)return;if(!/\.(csv|xlsx|xls)$/i.test(selected.name)){setError("فقط فایل CSV، XLS یا XLSX قابل قبول است.");return}setFile(selected);await analyze(selected)};
 const applyMapping=async()=>{if(file)await analyze(file,mapping)};
 const confirm=async()=>{if(!preview||!preview.validRows)return;setBusy(true);setError("");setProgress(1);try{const imported=await importSalesReport({fileName:preview.fileName,reportType:preview.reportType,rows:preview.rows},value=>setProgress(Math.max(1,value)));setProgress(90);await Promise.all([getReportSummary(),getReportCharts(),loadHistory()]);setResult(imported);window.dispatchEvent(new CustomEvent("tak:sales-imported"));localStorage.setItem("tak:last-sales-import",new Date().toISOString());setProgress(100)}catch(e:any){setError(e.response?.data?.message||"ثبت گزارش فروش انجام نشد.");setProgress(0)}finally{setBusy(false)}};
 const downloadSample=async()=>{try{setSampleLoading(true);await downloadSalesImportSample()}catch{setError("دانلود فایل نمونه انجام نشد.")}finally{setSampleLoading(false)}};
 const progressStage=result?"تکمیل شد":busy&&preview?"در حال ورود اطلاعات...":busy&&progress>55?"در حال اعتبارسنجی...":busy&&progress>20?"در حال خواندن فایل...":busy?"در حال آپلود...":preview?"آماده تأیید":"";
 return <main className="salesReportUpload" dir="rtl">
  <PageHeader eyebrow="SALES DATA IMPORT" title="ورود گزارش فروش" description="فایل فروش را نگاشت، پیش‌نمایش، اعتبارسنجی و سپس در CRM ثبت کنید." actions={<ActionButton className="secondary" onClick={()=>void downloadSample()} disabled={sampleLoading}><Download size={15}/>{sampleLoading?"در حال آماده‌سازی...":"دانلود فایل نمونه Excel"}</ActionButton>}/>
  <GlassCard className="importWizardSteps">{["نوع گزارش","آپلود فایل","ستون‌ها","نگاشت","پیش‌نمایش","تأیید"].map((title,index)=>{const current=result?6:preview?5:file?2:1;return <div key={title} className={index+1<=current?"done":""}><i>{(index+1).toLocaleString("fa-IR")}</i><span>{title}</span></div>})}</GlassCard>
  <GlassCard className="reportTypePanel"><header><CalendarRange/><div><h2>نوع گزارش فروش</h2><p>نوع گروه‌بندی زمانی فایل را پیش از آپلود انتخاب کنید.</p></div></header><div className="reportTypeGrid">{reportTypes.map(type=><button key={type.key} className={reportType===type.key?"active":""} onClick={()=>{setReportType(type.key);reset()}}><i><CalendarDays/></i><span><strong>{type.title}</strong><small>{type.description}</small></span><em/></button>)}</div></GlassCard>
  {!preview&&!result&&<GlassCard className="salesUploadPanel"><button className={"salesDropZone "+(busy?"uploading":"")} onClick={()=>inputRef.current?.click()} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void selectFile(event.dataTransfer.files[0])}}><input ref={inputRef} hidden type="file" accept=".csv,.xls,.xlsx" onChange={event=>void selectFile(event.target.files?.[0])}/><i><UploadCloud/></i><strong>{busy?"در حال خواندن فایل...":"انتخاب یا رها کردن فایل فروش"}</strong><span>فایل Excel یا CSV بدون محدودیت تعداد ردیف</span><Badge tone="purple">CSV / XLS / XLSX</Badge></button></GlassCard>}
  {progress>0&&<div className="salesUploadProgress"><span style={{width:progress+"%"}}/><small>{progressStage} · {progress.toLocaleString("fa-IR")}٪</small></div>}
  {error&&<div className="salesUploadMessage error"><AlertCircle/><span>{error}</span></div>}
  {preview&&!result&&<GlassCard className="detectedColumns"><header><div><span>مرحله ۳</span><h2>ستون‌های شناسایی‌شده</h2></div><Badge tone="info">{preview.headers.length.toLocaleString("fa-IR")} ستون</Badge></header><div>{preview.headers.map(header=><span key={header}>{header}</span>)}</div></GlassCard>}
  {preview&&!result&&<GlassCard className="salesImportAnalysis"><header><div><span>IMPORT ANALYSIS</span><h2>تحلیل هوشمند فایل</h2></div><Badge tone="info">Auto detected columns: {Object.values(preview.analysis).filter(Boolean).length}/4</Badge></header><div>{[["customer","مشتری"],["date","تاریخ"],["product","محصول"],["amount","مبلغ"]].map(([key,label])=>{const detected=preview.analysis[key as keyof typeof preview.analysis];return <span className={detected?"detected":"warning"} key={key}>{detected?<CheckCircle2/>:<AlertCircle/>}<b>{label}</b><small>{detected?"شناسایی شد":"ستون مرتبط پیدا نشد"}</small></span>})}</div></GlassCard>}
  {preview&&!result&&<><GlassCard className="columnMapping"><header><div><span>تطبیق ستون‌ها</span><h2>نگاشت ستون‌های فایل</h2></div><ActionButton className="secondary" disabled={busy} onClick={()=>void applyMapping()}><RefreshCw size={14}/> اعمال نگاشت</ActionButton></header><div>{mappingFields.map(([field,label,required])=><label key={field}><span>{label}{required&&<b>*</b>}</span><select value={mapping[field]||""} onChange={event=>setMapping(current=>({...current,[field]:event.target.value}))}><option value="">انتخاب نشده</option>{preview.headers.map(header=><option value={header} key={header}>{header}</option>)}</select></label>)}</div>{preview.missingColumns.length>0&&<p><AlertCircle/> Some columns could not be identified. Please review mapping.</p>}</GlassCard>
   <section className="salesPreviewStats"><GlassCard><FileSpreadsheet/><span>کل ردیف‌ها<strong>{preview.totalRows.toLocaleString("fa-IR")}</strong></span></GlassCard><GlassCard className="valid"><CheckCircle2/><span>معتبر<strong>{preview.validRows.toLocaleString("fa-IR")}</strong></span></GlassCard><GlassCard className="invalid"><AlertCircle/><span>دارای خطا<strong>{preview.invalidRows.toLocaleString("fa-IR")}</strong></span></GlassCard></section>
   <GlassCard className="salesGrouping"><header><span>خلاصه گروه‌بندی</span><b>{money(preview.groups.reduce((sum,group)=>sum+group.revenue,0))}</b></header><div>{preview.groups.slice(0,12).map(group=><article key={group.period}><strong>{group.period}</strong><span>{group.sales.toLocaleString("fa-IR")} فروش</span><b>{money(group.revenue)}</b></article>)}</div></GlassCard>
   <GlassCard className="salesPreviewTable"><header><div><span>پیش‌نمایش فایل</span><h2>{preview.fileName}</h2></div><Badge tone={preview.invalidRows?"warning":"success"}>{preview.invalidRows?preview.invalidRows.toLocaleString("fa-IR")+" خطا":"آماده ثبت"}</Badge></header><DataTable><thead><tr><th>تاریخ فروش</th><th>شماره فاکتور</th><th>نام مشتری</th><th>کد کالا</th><th>نام کالا</th><th>تعداد</th><th>مبلغ</th><th>اعتبارسنجی</th></tr></thead><tbody>{preview.rows.slice(0,150).map(row=><tr key={row.rowNumber} className={row.errors.length?"rowInvalid":""}><td>{row.date||"—"}</td><td>{row.invoiceNumber||"—"}</td><td><strong>{row.customerName||"—"}</strong><small>{row.customerPhone}</small></td><td>{row.productCode||"—"}</td><td>{row.productName||"—"}</td><td>{Number.isFinite(row.quantity)?row.quantity.toLocaleString("fa-IR"):"—"}</td><td className="reportAmount">{money(row.amount)}</td><td>{row.errors.length?<span className="salesRowErrors">ردیف {row.rowNumber.toLocaleString("fa-IR")}: {row.errors.join("، ")}</span>:<Badge tone="success">معتبر</Badge>}</td></tr>)}</tbody></DataTable><footer><ActionButton className="secondary" onClick={reset}>انصراف</ActionButton><ActionButton disabled={busy||!preview.validRows||preview.missingColumns.length>0} onClick={()=>void confirm()}>{busy?"در حال ثبت...":"تأیید و ورود "+preview.validRows.toLocaleString("fa-IR")+" فروش"}</ActionButton></footer></GlassCard></>}
  {result&&<GlassCard className="salesImportSuccess"><i><CheckCircle2/></i><h2>گزارش فروش پردازش شد</h2><p><strong>{result.importedRows.toLocaleString("fa-IR")}</strong> فروش ثبت و <strong>{result.failedRows.toLocaleString("fa-IR")}</strong> ردیف رد شد.</p><span>گزارش‌ها و داشبورد از داده‌های جدید استفاده می‌کنند.</span><div className="salesImportActions"><ActionButton onClick={reset}>ورود گزارش جدید</ActionButton><Link className="uiAction secondary" to="/reports">مشاهده گزارش فروش</Link></div></GlassCard>}
  {result&&result.errors.length>0&&<GlassCard className="salesImportErrors"><header><AlertCircle/><div><h3>جزئیات خطاهای ورود</h3><span>{result.errors.length.toLocaleString("fa-IR")} ردیف نیازمند بررسی</span></div></header><div>{result.errors.slice(0,50).map(item=><article key={item.row}><b>ردیف {item.row.toLocaleString("fa-IR")}</b><span>{item.message}</span></article>)}</div></GlassCard>}
  <GlassCard className="salesImportHistory"><header><div><History/><span><strong>تاریخچه ورود گزارش‌ها</strong><small>۳۰ فایل اخیر ثبت‌شده در CRM</small></span></div><ActionButton className="secondary" onClick={()=>void loadHistory()} disabled={historyLoading}><RefreshCw className={historyLoading?"spin":""} size={14}/> بروزرسانی</ActionButton></header>{historyLoading?<div className="historyLoading"><i/> در حال دریافت تاریخچه...</div>:history.length?<DataTable><thead><tr><th>نام فایل</th><th>نوع گزارش</th><th>تاریخ آپلود</th><th>آپلود کننده</th><th>تعداد رکورد</th><th>موفق</th><th>خطا</th><th>وضعیت</th><th>جزئیات</th></tr></thead><tbody>{history.map(item=><tr key={item.id} className="historyRow" onClick={()=>setSelectedImport(item)}><td><FileSpreadsheet size={14}/><strong>{item.fileName}</strong></td><td>{reportTypes.find(type=>type.key===item.reportType)?.title||item.reportType}</td><td><Clock3 size={13}/>{new Date(item.createdAt).toLocaleString("fa-IR")}</td><td>{item.uploadedBy?.name||"کاربر حذف‌شده"}</td><td>{item.totalRows.toLocaleString("fa-IR")}</td><td><span className="historySuccess">{item.importedRows.toLocaleString("fa-IR")}</span></td><td><span className="historyFailed">{item.failedRows.toLocaleString("fa-IR")}</span></td><td><Badge tone={item.status==="SUCCESS"?"success":item.status==="PARTIAL"?"warning":"danger"}>{item.status==="SUCCESS"?"موفق":item.status==="PARTIAL"?"بخشی":"ناموفق"}</Badge></td><td><button className="historyDetailsButton" type="button" onClick={event=>{event.stopPropagation();setSelectedImport(item)}}><Eye size={14}/> مشاهده</button></td></tr>)}</tbody></DataTable>:<div className="historyEmpty"><History/><span>هنوز گزارشی وارد نشده است.</span></div>}</GlassCard>
  <Modal open={Boolean(selectedImport)} title="جزئیات ورود گزارش فروش" onClose={()=>setSelectedImport(null)}>{selectedImport&&<div className="importDetails"><div className="importDetailsGrid"><span>نام فایل<strong>{selectedImport.fileName}</strong></span><span>نوع گزارش<strong>{reportTypes.find(type=>type.key===selectedImport.reportType)?.title||selectedImport.reportType}</strong></span><span>تاریخ آپلود<strong>{new Date(selectedImport.createdAt).toLocaleString("fa-IR")}</strong></span><span>آپلود کننده<strong>{selectedImport.uploadedBy?.name||"کاربر حذف‌شده"}</strong></span><span>ردیف موفق<strong className="historySuccess">{selectedImport.importedRows.toLocaleString("fa-IR")}</strong></span><span>ردیف ناموفق<strong className="historyFailed">{selectedImport.failedRows.toLocaleString("fa-IR")}</strong></span></div><section className="importDetailErrors"><h3>جزئیات ردیف‌های مشکل‌دار</h3>{selectedImport.errors.length?selectedImport.errors.map(error=><article key={`${error.row}-${error.message}`}><b>ردیف {error.row.toLocaleString("fa-IR")}</b><p>{error.message}</p></article>):<div className="historyEmpty"><CheckCircle2/><span>این Import بدون خطا انجام شده است.</span></div>}</section></div>}</Modal>
 </main>;
}
