import { BadRequestException,Injectable,NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';import { Repository } from 'typeorm';
import { Customer,FollowUp,Invoice,SalesCommission,User } from '../entities';
type Actor={id:number;role:string};
@Injectable()
export class SalesPerformanceService{
 constructor(@InjectRepository(User)private users:Repository<User>,@InjectRepository(Customer)private customers:Repository<Customer>,@InjectRepository(Invoice)private invoices:Repository<Invoice>,@InjectRepository(FollowUp)private followups:Repository<FollowUp>,@InjectRepository(SalesCommission)private commissions:Repository<SalesCommission>){}
 async getPerformance(actor:Actor){const users=await this.users.find({where:actor.role==='ADMIN'?{role:'SALES'}:{id:actor.id,role:'SALES'},order:{name:'ASC'}});const rows=await Promise.all(users.map(async user=>{const invoiceQuery=this.invoices.createQueryBuilder('invoice').innerJoin('invoice.customer','customer').where('customer.salespersonId=:userId',{userId:user.id}).andWhere("invoice.status != 'CANCELLED'");const followQuery=this.followups.createQueryBuilder('followup').where('followup.userId=:userId',{userId:user.id});const[customerCount,invoiceCount,totalRow,completedFollowUps,pendingFollowUps,lastInvoice,lastFollowUp,commission]=await Promise.all([this.customers.countBy({salespersonId:user.id}),invoiceQuery.clone().getCount(),invoiceQuery.clone().select('COALESCE(SUM(invoice.total),0)','total').getRawOne<{total:string}>(),followQuery.clone().andWhere("followup.status='DONE'").getCount(),followQuery.clone().andWhere("followup.status IN ('PENDING','OVERDUE')").getCount(),invoiceQuery.clone().select('MAX(COALESCE(invoice.invoiceDate,invoice.createdAt))','last').getRawOne<{last:string|null}>(),followQuery.clone().select('MAX(followup.createdAt)','last').getRawOne<{last:string|null}>(),this.commissions.findOneBy({userId:user.id})]);const totalSales=Number(totalRow?.total||0),percentage=Number(commission?.percentage||0),earned=totalSales*percentage/100,paid=Number(commission?.paidAmount||0);return{userId:user.id,name:user.name,customerCount,invoiceCount,totalSales,averageInvoice:invoiceCount?totalSales/invoiceCount:0,lastActivity:[lastInvoice?.last,lastFollowUp?.last].filter(Boolean).sort().at(-1)||null,completedFollowUps,pendingFollowUps,commissionPercentage:percentage,totalCommissionEarned:earned,paidCommission:paid,remainingCommission:Math.max(0,earned-paid)}}));return rows.sort((a,b)=>b.totalSales-a.totalSales)}
 async updateCommission(userId:number,data:any){const user=await this.users.findOneBy({id:userId,role:'SALES'});if(!user)throw new NotFoundException('Salesperson not found');const percentage=Number(data.percentage),paidAmount=Number(data.paidAmount);if(!Number.isFinite(percentage)||percentage<0||percentage>100)throw new BadRequestException('percentage must be between 0 and 100');if(!Number.isFinite(paidAmount)||paidAmount<0)throw new BadRequestException('paidAmount must be zero or greater');let item=await this.commissions.findOneBy({userId});if(!item)item=this.commissions.create({userId});item.percentage=percentage;item.paidAmount=paidAmount;return this.commissions.save(item)}
}
